### ISSUE TITLE
Auto deploy to production

### ISSUE THREAD

**Issue by neilenns** [neilenns/vatsim-plan-verifier#878]
Add to the release.yml file a step that deploys to the production environment via webhook

https://docs.github.com/en/actions/deployment/about-deployments/deploying-with-github-actions

```yaml
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: deploy
        # ...deployment-specific steps
```

The secrets are stored in GitHub already, use them like this:

```yaml
steps:
  - name: Hello world action
    with: # Set the secret as an input
      super_secret: ${{ secrets.SuperSecret }}
    env: # Or as an environment variable
      super_secret: ${{ secrets.SuperSecret }}
```
